name: Build Lazarus Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Free Pascal Compiler and Lazarus
      run: |
        # Установка FPC и Lazarus с выводом логов для диагностики
        choco install -y fpc --install-args="'/D=C:\Lazarus\fpc'"
        choco install -y lazarus --install-args="'/D=C:\Lazarus'"
        # Выводим список файлов в C:\Lazarus\fpc для проверки установки
        Get-ChildItem -Recurse C:\Lazarus\fpc

    - name: Verify FPC installation
      run: |
        # Проверяем, что FPC установлен правильно
        if (!(Test-Path "C:\Lazarus\fpc\3.2.0\bin\i386-win32\fpc.exe")) {
          throw "FPC not installed correctly!"
        }
        $env:PATH += ";C:\Lazarus\fpc\3.2.0\bin\i386-win32"
        $env:PATH += ";C:\Lazarus"

    - name: Verify project file exists
      run: |
        # Проверяем, что файл проекта существует
        if (!(Test-Path "./ipricese.lpi")) {
          throw "Project file not found: ipricese.lpi"
        }

    - name: Build project
      run: |
        # Строим проект
        & "C:\Lazarus\lazbuild.exe" ipricese.lpi
